version: "3"
services:
  postgres:
    image: postgres:16.2
    restart: always
    command: ["-c", "wal_level=logical", "-c", "max_wal_senders=10", "-c", "max_replication_slots=10"]
    environment:
      POSTGRES_USER: "dcp_user"
      POSTGRES_PASSWORD: "dcp_pass"
      POSTGRES_DB: "dcp_db"
      POSTGRES_HOST_AUTH_METHOD: trust
    network_mode: "host"
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - es01_data:/usr/share/elasticsearch/data
    networks:
      - dcpg_net
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=dcpg
      - discovery.type=single-node
      - ELASTIC_PASSWORD=dcpg_pass
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -I -o /dev/null http://localhost:9200 -w '%{http_code}' | grep -q '200'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      es01:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:7.17.11
    networks:
      - dcpg_net
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - kibana1_data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=dcpg_pass
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  postgres_data: null
  kibana1_data: null
  es01_data: null
networks:
  dcpg_net:
    driver: bridge